version: '3'
services:
    client:
        #build: .
        image: node:latest
        working_dir: /app
        volumes:
            - ./:/app:z
            - /app/node_modules
            - node-modules:/./node_modules
        tty: true
        command: bash -c 'npm install && npm run start'
        ports:
            - 3000:3000
    router:
        image: node:latest
        working_dir: /app
        volumes:
            - ./:/app:z
            - /app/node_modules
            - node-modules:/./node_modules
        command: bash -c 'npm install && node ./service'
    nginx:
        image: nginx
        volumes:
           - ./nginx:/etc/nginx/conf.d/:z
        ports:
            - 80:80
        tty: true
    redis:
        image: redis:latest
volumes:
    node-modules: # share node modules