version: '3.8'
services:
    client:
        build:
            context: .
            args: 
                NPM_TOKEN: ${NPM_TOKEN}
        volumes:
            - ./:/app:z
            - /app/node_modules
            - node-modules:/./node_modules
        tty: true
        ports:
            - 3000:3000
        command: bash -c 'npm run start'
    router:
        build:
            context: .
            args: 
                NPM_TOKEN: ${NPM_TOKEN}
        volumes:
            - ./:/app:z
            - /app/node_modules
            - node-modules:/./node_modules
        command: bash -c 'node ./service'
    nginx:
        image: nginx
        volumes:
           - ./nginx:/etc/nginx/conf.d/:z
        ports:
            - 80:80
        tty: true
        container_name: reverse-proxy
    # redis:
    #     image: redis:latest
volumes:
    node-modules: